export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILED = "LOGIN_FAILED"
export const LOGOUT = "LOGOUT";
export const FORGOT_PASSWORD = "FORGOT_PASSWORD";
export const VERIFY_EMAIL = "VERIFY_EMAIL";
export const VERIFY_OTP = "VERIFY_OTP";
export const REMOVE_EMAIL = "REMOVE_EMAIL";
export const REMOVE_FORGOT_PASSWORD = "REMOVE_FORGOT_PASSWORD";
export const RESSET_PASSWORD = "RESSET_PASSWORD";

export const SHOW_LOADER = "SHOW_LOADER"

export const SHOW_TOAST = "SHOW_TOAST";
export const DASHBOARD_COUNT = "DASHBOARD_COUNT";

export const ADMINITERTOR_DATA = "ADMINITERTOR_DATA";

export const ADMIN_DATA = "ADMIN_DATA";
export const ADMIN_DETAILS = "ADMIN_DETAILS";
export const ADMIN_STATUS_UPDATE = "ADMIN_STATUS_UPDATE";
export const UPDATE_ADMIN_PERVILEGE = "UPDATE_ADMIN_PERVILEGE";






export const VIEW_PROFILE_MODAL = "VIEW_PROFILE_MODAL"
export const CHANGE_PASSWORD_MODAL = "CHANGE_PASSWORD_MODAL"
export const ADD_ADMIN_MODAL = "ADD_ADMIN_MODAL"
export const ADMIN_EDIT_MODAL = "ADMIN_EDIT_MODAL"
export const EDIT_MODAL = "EDIT_MODAL"
export const DELETE_MODAL = "DELETE_MODAL"
export const PERVILEGE_MODAL = "PERVILEGE_MODAL"
export const PERVILEGE_LIST_MODAL = "PERVILEGE_LIST_MODAL"
export const ADD_ADMIN_GROUP_MODAL = "ADD_ADMIN_GROUP_MODAL"

 

export const SET_ACTIVE_ADMIN = "SET_ACTIVE_ADMIN"
export const SET_ACTIVE_ADMINITORTER = "SET_ACTIVE_ADMINITORTER"











